spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shinpo_db?useTimezone=true&serverTimezone=UTC
    username: shinpo_admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false

application-values:
  regex:
    email: ^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
    username: ^[a-zA-Z0-9._]{5,}$
    password: ^(?=.*[0-9])(?=.*[a-z])(?=.*[@#$%^&+=])(?=\S+$).{15,}$